Feature: Feature to Test Management RedlineCommissionUpfront functionality

  @Regression @005_Management_RedlineCommissionUpfront
  Scenario Outline: Management: <TestCase>: Test RedlineCommissionUpfront functionality for <Position>
    When Login: browser is open
    Then Login: Validate user is on login page
    Then Login: user enters valid username and password
    Then Login: Click Submit Button
    Then Login: Validate user is navigated to homepage
    Then Login: Subscription popup - Click on Later button
    Then Dashboard: Switch to Standard
    Then Management: Management Menu: Click
    Then Management: Management Menu: Search "<Position>" Position and Click to open details
    Then Management: Employment Package Tab: Click
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - Click on Edit button
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserCommission - Update Effective Date to "<CloserCommissionEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserCommission - Update Percentage from "<CloserCommissionPercentage>" to "<CloserCommissionPercentage_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserRedline - Update Effective Date to "<CloserRedlineEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserRedline - Select "<CloserRedlineType>" from Closer Redline Type Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserRedline - Update Amount from "<CloserRedline>" to "<CloserRedline_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserUpfront - Update Effective Date to "<CloserUpfrontEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserUpfront - Select "<CloserUpfrontCalculatedDropdownValue>" from Calculated Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserUpfront - Update Amount from "<CloserUpfrontAmount>" to "<CloserUpfrontAmount_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserWithheld - Update Effective Date to "<CloserWithheldEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserWithheld - Select "<CloserWithheldCalculatedDropdownValue>" from Calculated Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - CloserWithheld - Update Amount from "<CloserWithheldAmount>" to "<CloserWithheldAmount_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterCommission - Update Effective Date to "<SetterCommissionEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterCommission - Update Percentage from "<SetterCommissionPercentage>" to "<SetterCommissionPercentage_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterRedline - Update Effective Date to "<SetterRedlineEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterRedline - Select "<SetterRedlineType>" from Setter Redline Type Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterRedline - Update Amount from "<SetterRedline>" to "<SetterRedline_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterUpfront - Update Effective Date to "<SetterUpfrontEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterUpfront - Select "<SetterUpfrontCalculatedDropdownValue>" from Calculated Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterUpfront - Update Amount from "<SetterUpfrontAmount>" to "<SetterUpfrontAmount_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterWithheld - Update Effective Date to "<SetterWithheldEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterWithheld - Select "<SetterWithheldCalculatedDropdownValue>" from Calculated Dropdown
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SetterWithheld - Update Amount from "<SetterWithheldAmount>" to "<SetterWithheldAmount_Updated>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - SelfGen - Update Effective Date to "<SelfGenEffectiveDate>"
    Then Management: Employment Package Tab: RedlineCommissionUpfront SubSection - Click on Save button
    Examples:
      | TestCase | Position           | CloserCommissionEffectiveDate | CloserCommissionPercentage | CloserCommissionPercentage_Updated | CloserRedlineEffectiveDate | CloserRedlineType     | CloserRedline         | CloserRedline_Updated | CloserUpfrontEffectiveDate | CloserUpfrontAmount   | CloserUpfrontAmount_Updated | CloserUpfrontCalculatedDropdownValue | CloserWithheldEffectiveDate | CloserWithheldCalculatedDropdownValue | CloserWithheldAmount  | CloserWithheldAmount_Updated | SetterCommissionEffectiveDate | SetterCommissionPercentage | SetterCommissionPercentage_Updated | SetterRedlineEffectiveDate | SetterRedlineType     | SetterRedline         | SetterRedline_Updated | SetterUpfrontEffectiveDate | SetterUpfrontAmount   | SetterUpfrontAmount_Updated | SetterUpfrontCalculatedDropdownValue | SetterWithheldEffectiveDate | SetterWithheldCalculatedDropdownValue | SetterWithheldAmount | SetterWithheldAmount_Updated | SelfGenEffectiveDate  |
      | TC1      | Georgia Manager 1  |                               |                            |                                    |                            |                       |                       |                       | 03/01/2023                 | 0                     | 100                         | Per Sale                             |                             |                                       |                       |                              |                               |                            |                                    |                            |                       |                       |                       | 03/01/2023                 | 0                     | 10                          | Per KW                               | 03/01/2023                  | Per KW                                | 0                    | 0                            | 03/01/2023            |
#      | TC2      | Georgia Closer 1   |                               |                            |                                    |                            |                       |                       |                       | 03/01/2023                 | 100                   | 100                         | Per Sale                             | Should not be visible       | Should not be visible                 | Should not be visible | Should not be visible        | Should not be visible         | Should not be visible      | Should not be visible              | Should not be visible      | Should not be visible | Should not be visible | Should not be visible | Should not be visible      | Should not be visible | Should not be visible       | Should not be visible                |                             |                                       |                      |                              | Should not be visible |
      | TC3      | Georgia Setter 1   | Should not be visible         | Should not be visible      | Should not be visible              | Should not be visible      | Should not be visible | Should not be visible | Should not be visible | Should not be visible      | Should not be visible | Should not be visible       | Should not be visible                | Should not be visible       | Should not be visible                 | Should not be visible | Should not be visible        |                               |                            |                                    |                            |                       |                       |                       | 03/01/2023                 | 500                   | 75                          | Per KW                               |                             |                                       |                      |                              | Should not be visible |
      | TC4      | Tennessee Manager  | 04/01/2023                    | 50                         | 40                                 | 04/01/2023                 |                       | 2.60                  | 2.50                  |                            |                       |                             |                                      |                             |                                       |                       |                              | 04/01/2023                    | 50                         | 55                                 | 04/01/2023                 |                       | 3.0                   | 3.1                   |                            |                       |                             |                                      | 04/01/2023                  | Per KW                                | 0                    | 0                            | 04/01/2023            |
      | TC5      | Tennessee Closer 1 | 04/01/2023                    | 40                         | 50                                 | 04/01/2023                 |                       | 2.8                   | 2.85                  |                            |                       |                             |                                      |                             |                                       |                       |                              | Should not be visible         | Should not be visible      | Should not be visible              | Should not be visible      | Should not be visible | Should not be visible | Should not be visible | Should not be visible      | Should not be visible | Should not be visible       | Should not be visible                |                             |                                       |                      |                              | Should not be visible |
      | TC6      | Tennessee Setter 1 | Should not be visible         | Should not be visible      | Should not be visible              | Should not be visible      | Should not be visible | Should not be visible | Should not be visible | Should not be visible      | Should not be visible | Should not be visible       | Should not be visible                | Should not be visible       | Should not be visible                 | Should not be visible | Should not be visible        | 04/01/2023                    | 60                         | 50                                 | 04/01/2023                 |                       | 3.0                   | 2.95                  |                            |                       |                             |                                      |                             |                                       |                      |                              | Should not be visible |
      | TC7      | VP of Sales        | 04/01/2023                    | 20                         | 30                                 | 04/01/2023                 |                       | 2.20                  | 2.15                  |                            |                       |                             |                                      |                             |                                       |                       |                              | Should not be visible         | Should not be visible      | Should not be visible              | Should not be visible      | Should not be visible | Should not be visible | Should not be visible | Should not be visible      | Should not be visible | Should not be visible       | Should not be visible                |                             |                                       |                      |                              | Should not be visible |
